---
- name: Update package list
  become: yes
  become_method: sudo
  apt: upgrade=dist update_cache=yes

- name: Install packages
  apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - bash
    - curl
    - git
    - htop
    - nmap
    - nodejs
    - python
    - python-pip
    - python3
    - python3-pip
    - python-pycurl
    - vim
    - tmux
    - wget
    - zsh

- name: Change shell to ZSH
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name=root

- name: Install FASD
  become: yes
  become_method: sudo
  copy: src=fasd dest=/usr/local/bin/fasd mode=755